### ISSUE TITLE
Skyline-r-Mythic-Tools // french

### ISSUE THREAD

**Issue by kahlano** [Paojy/Skyline-r-Mythic-Tools#1]
Hello, being a French player, I play with the game in French. I wanted to install your addon that looks really good. Once installed I can see it installed (https://www.noelshack.com/2018-17-4-1524755435-smt.jpg), but I can not open it (/ smt) to configure it. 

Does not it work with the game in French?

thank you in advance

**Comment by kahlano** [comment]
thank you for your quick reply.

I remain waiting for your development.

good luck !

**Comment by Vardex** [comment]
The command /smt is already used in the french localisation of the game.

`SLASH_CLEAR_WORLD_MARKER2 = "/smt";`

smt standing for "Suppr Marqueur Terrain"

#3 is fixing this problem.

**Comment by kahlano** [comment]
i hope soon ;)
